### GET ALL 
GET http://localhost:3001/api/persons

### GET PERSON WITH ID 602121083bdf9f631c0ba59f // EXISTING
GET http://localhost:3001/api/persons/602121083bdf9f631c0ba59f

### GET PERSON WITH ID 602121083bdf9f631c0ba50f // NON-EXISTING
GET http://localhost:3001/api/persons/602121083bdf9f631c0ba50f

### GET PERSON WITH ID 99999 // MAL-FORMED
GET http://localhost:3001/api/persons/99999

### DELETE PERSON WITH ID xxxx
DELETE http://localhost:3001/api/persons/602121083bdf9f631c0ba59f

### CREATE PERSON
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Test name",
    "number": "1111111"
}

### CREATE A PERSON THAT DOESN'T MATCH VALIDATOR
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Test name",
    "number": 11111111
}

### UPDATE PERSON WITH ID XXXX
PUT http://localhost:3001/api/persons/60212c1f7e80f555901d092c HTTP/1.1
Content-Type: application/json

{
    "name": "Updated person",
    "number": "999-999999"
}